import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { app } from '../firebaseConfig'
import { getAuth, createUserWithEmailAndPassword, GoogleAuthProvider, GithubAuthProvider, signInWithPopup } from "firebase/auth"
import { useState } from 'react'
import { useRouter } from 'next/router'

export default function Register() {
    const auth = getAuth()
    const googleProvider = new GoogleAuthProvider();
    const githubProvider = new GithubAuthProvider()
    const router = useRouter()
    const [email, setEmail] = useState("")
    const [password, setPassword] = useState("")

    const signUp = () => {
        createUserWithEmailAndPassword(auth, email, password)
            .then((response) => {
                router.push('/home')
            })
    }
    const signUpWithGoogle = () => {
        signInWithPopup(auth, googleProvider)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response.user)
                router.push('/home')
            })
    }
    const signUpWithGithub = () => {
        signInWithPopup(auth, githubProvider)
            .then((response) => {
                sessionStorage.setItem('Token', response.user.accessToken)
                console.log(response.user)
            })
    }

    // useEffect(() => {
    //     let token = sessionStorage.getItem('Token')

    //     if (token) {
    //         router.push('/home')
    //     }
    // }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1>Register</h1>
                <input
                    placeholder='Email'
                    className={styles.inputBox}
                    value={email}
                    type="email"
                    onChange={(e) => setEmail(e.target.value)}
                />
                <input
                    placeholder='Password'
                    className={styles.inputBox}
                    value={password}
                    type='password'
                    onChange={(e) => setPassword(e.target.value)}
                />
                <button className={styles.button}
                    onClick={signUp}
                >Sign Up</button>
                <br />
                <button className={styles.googleAlt}
                    onClick={signUpWithGoogle}
                >Sign Up with Google</button>
                <br />
                <button className={styles.googleAlt}
                    onClick={signUpWithGithub}
                >Sign Up with GitHub</button>
            </main>

        </div>
    )
}